name: vaayusphere
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sidebarx: ^0.17.1
  http: ^1.2.2
  provider: ^6.1.2
  geekyants_flutter_gauges: ^1.0.4
  fl_chart: ^0.70.1
  syncfusion_flutter_charts: ^27.2.5
  mrx_charts: ^0.1.3
  graphic: ^2.5.0
  card_loading: ^0.3.2
  loading_indicator: ^3.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_native_splash: ^2.4.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
    - assets/gifs/air.gif
    - assets/Icons/sun.png

flutter_native_splash:
 
  color: "#000000"
  branding: assets/logo/logo.png
  android_12:
    # image: assets/android12splash.png

    # Splash screen background color.
    color: "#000000"

    

  
  color_web: "#000000"
  web_image_mode: center
  
